### ISSUE TITLE
Mercure hub filename cannot be empty

### ISSUE THREAD

**Issue by thehatami** [symfony/mercure-bundle#10]
implementing first hello word according [here](https://symfony.com/blog/symfony-gets-real-time-push-capabilities) got this error. why? what is this file and where?

```
Unable to publish the update to the Mercure hub: file_get_contents(): Filename cannot be empty
```

UPDATED
i change many params and last get:
```
Unable to publish the update to the Mercure hub: file_get_contents(http://127.0.0.1:3000/hub): failed to open stream: HTTP request failed! HTTP/1.0 401 Unauthorized
```

**Comment by sidikhalifa** [comment]
you can put your code?

**Comment by dunglas** [comment]
`HTTP/1.0 401 Unauthorized` means that the JWT you provide isn't valid. It's probably not signed with the same key than the one set for the hub.

Can you try to follow these steps? https://github.com/dunglas/mercure#401-unauthorized

**Comment by dunglas** [comment]
A better error message will now be thrown since the Mercure Symfony component now switched to HttpClient.
