### ISSUE TITLE
Can not access "target" property from the mercure panel in profiler

### ISSUE THREAD

**Issue by NUMERICKS** [symfony/mercure-bundle#31]
Hi, 

I actually get that error when I try to open the mercure panel in my profiler. 

`Neither the property "targets" nor one of the methods "targets()", "gettargets()"/"istargets()"/"hastargets()" or "__call()" exist and have public access in class "Symfony\Component\Mercure\Update".`

Error in : mercure.html.twig (line 70)

**Comment by chalasr** [comment]
Will be fixed by #28
