### ISSUE TITLE
Can't transfer cookie to hub

### ISSUE THREAD

**Issue by sidikhalifa** [symfony/mercure-bundle#5]
Hello, 
I use MercuryBundle for my project symfony. It work when I notify everyone, however, if I want to notify a particular user it does not work!, i can not transfer the **cookie** that has been generating to my hub.
Still, I put in my javascript option `withCredentials: true`:

`const eventSource = new EventSource(url, {withCredentials: true});`

thanks

**Comment by dunglas** [comment]
Hi,

Be sure to read this issue: https://github.com/dunglas/mercure/issues/63#issuecomment-475239674

**Comment by sidikhalifa** [comment]
yes I tried first : 

`JWT_KEY='aVerySecretKey' ADDR='localhost:3000' ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=http://tuto.my-website.com ./mercure`

after I tried to put it on the same domain : 

`JWT_KEY='aVerySecretKey' ADDR='tuto.my-website.com:3000' ALLOW_ANONYMOUS=1 CORS_ALLOWED_ORIGINS=http://tuto.my-website.com ./mercure`
after I ended up with a 401 error !


For the second case with the **ADDR** parameter I could not put the protocol because the Mercure generate an error **too many parameter**

**Comment by dunglas** [comment]
ADDR should be `:3000`. So the URL of your Symfony app is `http://tuto.my-website.com` and the one of your hub is `http://tuto.my-website.com:3000/hub` right?
Can you paste the code you use to set the cookie and the error you get in the Chrome console please?

**Comment by sidikhalifa** [comment]
hello kevin, 

I put the video on youtube, you can read it on this link : 
https://www.youtube.com/watch?v=SeBES4TJfZ8

and here is the **link** of my little mercurebundle test project if you ever want to test it yourself the  password for users is `1234`
https://github.com/short-edition/tuto

thanks

**Comment by dunglas** [comment]
Ok, the problem isn't related to cookies (if the cookie wasn't send properly the client would not even get the 401 error, it would just be connected anonymously).
The issue is most likely related to the JWT key being different in the Symfony app and in the Mercure hub. Be sure to double-check https://github.com/dunglas/mercure#401-unauthorized

**Comment by sidikhalifa** [comment]
thank you kevin, I found the solution for my problem that it came from the way I wrote my Token you were absolutely right :wink: 
In my subscribers I put this:
``````
