### ISSUE TITLE
Publish with hub doesn't work

### ISSUE THREAD

**Issue by prugala** [symfony/mercure-bundle#70]
I have a problem with publishing events with Hub service. Mercure returns error 400 and message `"Missing "topic" parameter` when I'm using pure PHP code to send requests all works correctly.

Bundle version: 0.3.4
Component: v0.6.1
Symfony: 5.4

Bundle configuration is simplest:
```
mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            jwt: '%env(MERCURE_JWT_TOKEN)%'
```

Example code:
```
$update = new Update(
            'test',
            json_encode(['key' => 'updated value 4'])
        );

        $data = $this->hub->publish($update);

        var_dump($data);

        define('DEMO_JWT', $this->hub->getProvider()->getJwt());

        $postData = http_build_query([
            'topic' => 'test',
            'data' => json_encode(['key' => 'updated value 3']),
        ]);

        echo file_get_contents($this->hub->getUrl(), false, stream_context_create(['http' => [
            'method'  => 'POST',
            'header'  => "Content-type: application/x-www-form-urlencoded\r\nAuthorization: Bearer ".DEMO_JWT,
            'content' => $postData,
        ]]));
```

`var_dump($data);` returns `Missing "topic" parameter`
as you can see in pure PHP code I'm using values (URL and token) from HUB and publish works.

**Comment by prugala** [comment]
@dunglas I found what is the problem but I'm not sure is it a problem with the Symfony component or with Mercure?

Symfony Hub doesn't send `Content-Type application/x-www-form-urlencoded` header, but I don't know if that should be sent or Mercure should support all requests as `application/x-www-form-urlencoded`?

**Comment by dunglas** [comment]
Check this example out: https://github.com/dunglas/mercure/blob/main/examples/publish/php.php

**Comment by prugala** [comment]
Fixed in https://github.com/symfony/mercure/pull/81
