### ISSUE TITLE
Add support for lcobucci/jwt v5

### ISSUE THREAD

**Issue by bobvandevijver** [symfony/mercure-bundle#76]
This bundle currently requires lcobucci/jwt `^3.4|^4.0` and is therefor the only dependency that is currently blocking me to upgrade to the latest JWT lcobucci/jwt release.

Note that the v5 release might need some work here as the release removes deprecated components, makes PHP 8.1 the minimum required version and ships some API improvements.

**Comment by dunglas** [comment]
`lcobucci/jwt` is already supported in the master branch. We'll tag a release soon. https://github.com/symfony/mercure-bundle/pull/72

**Comment by dunglas** [comment]
Done!

**Comment by bobvandevijver** [comment]
Sorry about that, should have checked the master branch first! Thanks for the tag 😃
